Repository jenkinsci/gerrit-trigger-plugin, pull requests merged in 2020-10, with the labels that each got.

#413 Introduce custom handling of aborted jobs
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/Config.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/IGerritHudsonTriggerConfig.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/extensions/GerritTriggeredBuildListener.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpander.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/model/BuildMemory.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTriggerDescriptor.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/data/SkipVote.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/utils/Logic.java
  src/main/resources/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritServer/index.jelly
  src/main/resources/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritServer/index_ja.properties
  src/main/resources/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger/config.jelly
  src/main/resources/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger/config_ja.properties
  src/main/webapp/help-GerritBuildAbortedCodeReview.html
  src/main/webapp/help-GerritBuildAbortedCodeReview_ja.html
  src/main/webapp/help-GerritBuildAbortedVerified.html
  src/main/webapp/help-GerritBuildAbortedVerified_ja.html
  src/main/webapp/help-GerritVerifiedCmdBuildAborted.html
  src/main/webapp/help-GerritVerifiedCmdBuildAborted_ja.html
  src/main/webapp/trigger/help-BuildAbortedMessage.html
  src/main/webapp/trigger/help-BuildAbortedMessage_ja.html
  src/main/webapp/trigger/help-GerritBuildAbortedCodeReview.html
  src/main/webapp/trigger/help-GerritBuildAbortedVerified.html
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/ConfigTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/dependency/DependencyQueueTaskDispatcherTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpanderParameterizedTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpanderSkipVoteParameterTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpanderTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/model/BuildMemoryTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritItemListenerTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTriggerTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/mock/MockGerritHudsonTriggerConfig.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/mock/Setup.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/utils/MockPluginCheckerConfig.java
Labels: enhancement

#361 Abort topic once
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger.java
Labels: regression

#417 update gerrit-events to latest version
  pom.xml
Labels: dependencies
