Repository jenkinsci/gerrit-trigger-plugin, pull requests merged in 2020-02, with the labels that each got.

#410 Fix bug in abort build configuration
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger.java
Labels: regression

#411 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: chore

#409 Prevent forbiddenFilePaths from corrupting following filePath matches
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/data/GerritProject.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/data/GerritProjectForbiddenFilesTest.java
Labels: bug
