Repository jenkinsci/gerrit-trigger-plugin, pull requests merged in 2021-05, with the labels that each got.

#436 JENKINS-53250: Fix warnings what configuration-as-code is not installed
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/GerritJcascConfigurator.java
Labels: regression

#441 feat: support incrementals
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#439 Only store events from configured server
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/playback/GerritMissedEventsPlaybackManager.java
Labels: bug
