Repository jenkinsci/gerrit-trigger-plugin, pull requests merged in 2022-11, with the labels that each got.

#479 [JENKINS-69779] Fix broken icons in Gerrit settings
  src/main/webapp/js/server-table.js
Labels: bug, ui

#468 [JENKINS-65349] Feature voting patchsets with the same topic
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/PluginImpl.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/Config.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/IGerritHudsonTriggerConfig.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/GerritNotifier.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/GerritNotifierFactory.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpander.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ToGerritRunListener.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/job/ssh/BuildCompletedCommandJob.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/job/ssh/BuildStartedCommandJob.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/notification/INotification.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/notification/Notification.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/notification/NotificationBuildCompleted.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/notification/NotificationBuildStarted.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/notification/NotificationCommands.java
  src/main/resources/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritServer/index.jelly
  src/main/webapp/help-GerritVotePatchSetsWithSameTopic.html
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpanderTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ToGerritRunListenerTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/mock/MockGerritHudsonTriggerConfig.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/spec/VoteSameTopicTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/utils/MockPluginCheckerConfig.java
  src/test/java/com/sonymobile/tools/gerrit/gerritevents/mock/SshdServerMock.java
Labels: enhancement

#476 Fix SSH connection leaks
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/config/GerritJcascConfigurator.java
Labels: regression

#482 [JENKINS-70045] Fix active to wip state change triggers build
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTriggerTest.java
Labels: enhancement
