Repository jenkinsci/gerrit-trigger-plugin, pull requests merged in 2023-07, with the labels that each got.

#491 [JENKINS-71645] Fix granting Project list fetch interval parameter
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritProjectListUpdater.java
Labels: bug

#492 [JENKINS-71645] Fix Project list fetch interval parameter
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritProjectListUpdater.java
Labels: regression

#494 Remove usages of Prototype
  pom.xml
  src/main/resources/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritServer/index.jelly
Labels: internal

#495 [JENKINS-71645] Fix unit for project list fetch interval
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritProjectListUpdater.java
Labels: bug

#493 [JENKINS-66535] Fix situation when failed builds are missing and only successful builds remain
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpander.java
  src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/job/rest/BuildCompletedRestCommandJob.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpanderSkipVoteParameterTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/gerritnotifier/ParameterExpanderTest.java
  src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/mock/Setup.java
Labels: bug
